maximum_name_length: 50
maximum_email_length: 255
minimum_password_length: 6
gravatar_size: 80
remember_me: "1"
remember_me_not: "0"
gravatar_medium: 50
gravatar_small: 30
default_from_email: "noreply@example.com"
address: "smtp.gmail.com"
port: 587
domain: "gmail.com"
authentication: "plain"
enable_auto: true
password_expire: 2
maximum_content_length: 140
index_per_page: 20
maximum_upload_size: 5
